### ISSUE TITLE
VP-INDEX

### ISSUE THREAD

**Issue by Ammarbr** [ejp-rd-vp/vp-portal-issues#1]
**Describe your problem.**

According to [THIS LIST](https://ejprd.sharepoint.com/:x:/r/sites/pillar2-central9/_layouts/15/Doc.aspx?sourcedoc=%7B294F99DD-FCF7-410B-9A9C-B29BF54316BA%7D&file=VP_scaleup_Resources-Component_Planning.xlsx&action=default&mobileredirect=true&cid=c03d36b0-e28d-4d2b-ba6b-5e30cd11a1a6l) there is 19 Resources that have to be integrated in VP-PORTAL until 30/06/2023 but we are missing information about the resources FAIRVasc, Registry ERN EURO-NMD (EURO-NMD Registry ), Registry ERN-Skin (ERN-Skin REGISTRY), 
Registry ERN CRANIO (ERN CRANIO registry ), Registry VASCERN (VASCA), EGA, Metabolights, Infrafrontier even after adding all available information from [the onboarding list](https://ejprd.sharepoint.com/sites/pillar2-central9/Lists/Onboarding%20Resources/AllItems.aspx)

Required attributes for Level 1: 
- resourceName
- resourceHomePage
- resourceDescription
- resourceType
- logo (optional)

Required attributes for Level 2:
- resourceAddress
- queryType
- queryable

**Describe the solution you'd like**

We welcome any potential solutions, including:

1. Enhancing the [VP-INDEX ENDPOINT](https://qb.index.vp.ejprarediseases.org/resources) to ensure that all required information is provided and accessible.
2. Simply updating the missing information in the [JSON file](https://ejprd-my.sharepoint.com/:u:/g/personal/ammar_barakat_ejprd-project_eu/EViRyWYbQOtCnZpkuTo-59sBF1j0KueEI_bVRYi0SldhHQ?e=bs8aJQ) and we will continue to utilize the hardcoded list within the portal's infrastructure.

**Additional context**

If you come across any inaccuracies or incorrect information within the static resources list, please don't hesitate to reach out to us, even if it pertains to resources not specifically mentioned above.

**Comment by HaddadTala** [comment]
The onboarding team (@nirupamaBenis @brunasv @carles) is filling in the missing info in the JSON file for the timebeing, but the metadata team (@henrietteharmse @Orphanet ) will be meeting with @luizbonino and @markwilkinson to resolve the inconsistencies between the metadata schema and the FDP implementations. The beaconized catalogue API needs to be updated as well, as it's missing some metadata fields too.
