### ISSUE TITLE
HTTP 429 - Error message

### ISSUE THREAD

**Issue by kkr-ait** [ejp-rd-vp/vp-portal-issues#11]
**Describe your problem.**

Search is not possible because I hit an API rate limit. 

**If it is a bug name steps to reproduce**

Perform multiple searches on the discovery portal

**If it is a bug complete the following information:**

- Version: 1.0
- OS: Windows
- Browser: Firefox

**Describe the solution you'd like**

When the rate limit is hit, the error can only be seen in the Browser's Javascript console, but no message is displayed to the end-user. This is a bit confusing, as (once the rate limit is reached) the portal does not seem to respond to queries at all.
Maybe a small message in the UI would be good in this case inviting the user to try later again.

**Additional context**

-

**Comment by Ammarbr** [comment]
@kkr-ait Thank you for providing your feedback. I'm glad to inform you that the issue has been successfully [RESOLVED](https://github.com/ejp-rd-vp/vp-dp-backend/issues/15).
