### ISSUE TITLE
Update VP Index Middleware & VP Portal aligning with metadataschema

### ISSUE THREAD

**Issue by vabishaa** [ejp-rd-vp/vp-portal-issues#14]
**Describe your problem.**

Align the VP Index Middleware and VP Portal with the current metadata schema

**Describe the solution you'd like**

Currently a hardcoded list of connected resources is used, which should be replaced by querying the VP Index Middleware. Moreover, the JSON structure is not aligned with the current metadata schema and should therefore be updated.

**Additional context**

Will be dicussed in the OA meeting (Current state https://github.com/ejp-rd-vp/vp-portal-issues/issues/1)
Cuurent JSON File schema: [JSON file](https://ejprd-my.sharepoint.com/:u:/g/personal/ammar_barakat_ejprd-project_eu/EViRyWYbQOtCnZpkuTo-59sBF1j0KueEI_bVRYi0SldhHQ?e=bs8aJQ)

**Comment by Ammarbr** [comment]
@markwilkinson I have a quick question regarding the metaDataSchema. According to the [documentation](https://github.com/ejp-rd-vp/resource-metadata-schema/blob/master/template/README.md), the available resource types are: bioBank, patientRegistry, guideline, dataset, dataService, and catalog. However, I noticed that there is a mention of an 'organisation' and a 'distribution'. are these resourceTypes too?

**Comment by markwilkinson** [comment]
I'm not sure I understand the question... both "organization" and "distribution" are included in both the diagram and the text... and are both resources (using the general definition of a "resource" in the linked data context...)

Can you be more specific?

**Comment by Ammarbr** [comment]
@markwilkinson Of course, I will make an effort to provide more specificity. On the [VP Network Resources](https://vp.ejprarediseases.org/discovery/sources) page, our goal is to present each resourceType along with its associated icon. 

Which resourceTypes would you recommend displaying on that page? 

For instance, when it comes to the resourceType 'DataSet,' we believe it would be more meaningful to disregard the 'distribution' aspect and simply mark the resource as a 'DataSet'.

**Comment by ammarbarakat** [comment]
See #46
