### ISSUE TITLE
Adding Section/Tab: FAQ + About 

### ISSUE THREAD

**Issue by HaddadTala** [ejp-rd-vp/vp-portal-issues#15]
Suggested addition of an 'About' page: https://github.com/ejp-rd-vp/vp-dp-frontend/blob/develop/assets/md/about.md

See proposed text modifications in attached file.
[FAQ-ana.docx](https://github.com/ejp-rd-vp/vp-portal-issues/files/11935310/FAQ-ana.docx)

**Comment by HaddadTala** [comment]
@Ammarbr The mindmap is the same as the one linked in the expore tab: https://resourcemap.ejprarediseases.org/#/

**Comment by Ammarbr** [comment]
Thank you @HaddadTala!

**Comment by Ammarbr** [comment]
related issues: [#64](https://github.com/ejp-rd-vp/vp-dp-frontend/issues/64)

**Comment by HaddadTala** [comment]
@Ammarbr @vabishaa could you kindly also add a link to the 'About' section at the end of the main text (see photo below)
![image](https://github.com/ejp-rd-vp/vp-portal-issues/assets/91144909/47838fd9-9e78-4508-b4e9-b42957fd14cc)
