### ISSUE TITLE
Missing ERKReg resource in search page

### ISSUE THREAD

**Issue by joseramgar** [ejp-rd-vp/vp-portal-issues#17]
**Describe your problem.**

When performing a search, ERKReg does not appear in the results page anymore. 

<img width="923" alt="ERKReg_VP_V1" src="https://github.com/ejp-rd-vp/vp-portal-issues/assets/69801108/3e8cb16b-e703-455b-a1d2-c4587dd52a2b">

**If it is a bug complete the following information:**

- Version: https://vp.ejprarediseases.org/
- OS: Windows
- Browser: Firefox

**Describe the solution you'd like**

ERKReg results visible when searching

**Comment by Orphanet** [comment]
As far I can see, the "extension" is needed through "related Orphanet Codes" using hierachies
If you pick Rare Genetic Renal (menu on right side)
![erk1](https://github.com/ejp-rd-vp/vp-portal-issues/assets/7070239/1f14244f-568f-457f-950d-f8cf81c94aa2)

the result should be there:
![erk2](https://github.com/ejp-rd-vp/vp-portal-issues/assets/7070239/11e870da-fcc2-4410-b793-65ab4a4312b6)

**Comment by vabishaa** [comment]
@joseramgar and @rini21 Could you check this issue and give an update or close it if it is solved. Thanks.

**Comment by joseramgar** [comment]
@vabishaa @rini21 The issue seems to be solved already. Thank you for your help, everyone!
