### ISSUE TITLE
Ensure imprint requirements compliance in europe

### ISSUE THREAD

**Issue by Ammarbr** [ejp-rd-vp/vp-portal-issues#2]
**Describe your problem.**

The current implementation of the [IMPRINT](https://directory.ejp.vp.bbmri-eric.eu/imprint) on VP-PORTAL does not meet the minimum requirements set by German law (I assume for europe too). In order to comply with the legal regulations, the imprint must include the following information:

1. Name: The imprint should display the full name of natural persons (including first name and surname) and the complete company name for legal persons, along with the first name and surname of the authorized representative.

2. Legal Form: For legal entities, the imprint should clearly indicate the legal form, such as "GmbH" or "AG."

3. Address: The imprint should provide a complete postal address, including street, house number, postal code, and city. Note that a post office box is not considered sufficient.

4. Contact Information: The imprint should include contact details that enable quick communication both electronically and non-electronically. Typically, this includes an email address and telephone number.

5. Tax Identification Numbers: If available, the imprint should feature the sales tax or business tax identification number.

6. Registration Numbers: If applicable, the imprint should display the registration numbers from the commercial, association, partnership, company, or cooperative register.

**Describe the solution you'd like**

Ensure that the imprint on VP-PORTAL complies with these minimum european requirements.

**Additional context**

@HaddadTala could you help us to ensure that the imprint on VP-PORTAL complies with the minimum european requirements? 
This will help us meet the legal obligations and maintain transparency with our users and authorities.

**Comment by HaddadTala** [comment]
@Ammarbr @vabishaa please find the legal entity information below. You can also see how it is formatted in the EJP RD website next to the EU flag and the funding details (https://www.ejprarediseases.org/):

EJP RD Coordination Office
INSERM 
Hôpital Charles-Foix
7 avenue de la République
94200 Ivry-sur-Seine
France

Email: coordination@ejprarediseases.org

**Comment by Ammarbr** [comment]
I appreciate your assistance, @HaddadTala  
I'm glad to inform you that the [ISSUE](https://github.com/ejp-rd-vp/vp-dp-frontend/issues/35) been resolved, and the accurate imprint is now available [ONLINE](https://directory.ejp.vp.bbmri-eric.eu/imprint)
