### ISSUE TITLE
Choosing multiple genders is not working properly for beacon queries

### ISSUE THREAD

**Issue by Ammarbr** [ejp-rd-vp/vp-portal-issues#21]
**Describe your problem.**

Currently, the feature allowing users to choose multiple genders when performing beacon queries is experiencing functionality problems. This issue hinders the proper selection of multiple genders, resulting in inaccurate query results.

**If it is a bug name steps to reproduce**

1. Go to vp-portal
2. Search for an orphaCode (e.g. 778)
3. Select multiple genders and send the query

**Describe the solution you'd like**

Searching for multiple genders should work properly.

**Additional context**

Thank you for bringing the issue to our attention, @rini21

**Comment by Ammarbr** [comment]
Related issues: [#18](https://github.com/ejp-rd-vp/vp-dp-backend/issues/18)

**Comment by rini21** [comment]
### The issue persists, and does not show accurate results for L2 resources. Tested with multiple resources. 

Example: In GPAP, querying via Postman for 778 AND (Male or Female) results in 93 (as below):
![image](https://github.com/ejp-rd-vp/vp-portal-issues/assets/24955128/2aa570d1-4346-4cca-b981-e789c33da98c)

However, this is not the case when tested in the VP-Portal as GPAP itself is not shown in the results:
![image](https://github.com/ejp-rd-vp/vp-portal-issues/assets/24955128/30b364f7-49de-4ab4-adce-16eb5ad90147)

**Comment by Ammarbr** [comment]
The resource does not appear in the results because the response time exceeds the time limit allowed by vp-portal. In order to conduct tests, we have increased the timeout duration. Kindly perform another test and verify if everything is functioning correctly. Thank you. @rini21

**Comment by rini21** [comment]
Working as expected after the fix. Thanks @Ammarbr!
