### ISSUE TITLE
Country filter is ignored

### ISSUE THREAD

**Issue by kkr-ait** [ejp-rd-vp/vp-portal-issues#23]
When searching for

- orpha code 730
- Patient registries
- Country: Austria

I get 1014 results from ERKREG. If I set the filter to all countries, I get the same number of results

**Comment by kkr-ait** [comment]
@Ammarbr @vabishaa @HaddadTala

**Comment by Ammarbr** [comment]
As far as I know, the country filter cannot be applied to the individual endpoints (such as ERKReg, Ithaca, Genturis). Please feel free to correct me if I'm mistaken, @rini21

**Comment by rini21** [comment]
You are correct @Ammarbr, country (and other [catalog filters](https://github.com/ejp-rd-vp/vp-api-specs#catalogs)) will not be applicable to L2 resources, hence, these filters will be ignored and respond with results for Orpha 730.
