### ISSUE TITLE
Label "VpContentDiscovery"

### ISSUE THREAD

**Issue by kkr-ait** [ejp-rd-vp/vp-portal-issues#26]
In the VP network resources section, a label "VpContentDiscovery" is displayed. Is this intentional or should we have a more human-friendly lable?

**Comment by Ammarbr** [comment]
The decision regarding this matter was made two weeks ago in issue [#45](https://github.com/ejp-rd-vp/resource-metadata-schema/issues/45) If you believe it should be modified or expressed differently, please feel free to open the [main issue](https://github.com/ejp-rd-vp/resource-metadata-schema/issues/45) and engage in a discussion with others. Many thanks.

**Comment by kkr-ait** [comment]
Perfect - thx for the clarification.
