### ISSUE TITLE
AAI Login screen

### ISSUE THREAD

**Issue by kkr-ait** [ejp-rd-vp/vp-portal-issues#28]
When trying to login using AAI I am presented with a "Google option"

![AAI_Login_Screen](https://github.com/ejp-rd-vp/vp-portal-issues/assets/136702964/a7231a49-6658-4463-8b6d-7bb2d13fa79a)

@HaddadTala - if I am correct we did not want Google/Apple/LinkedIn as login options, right? So, consequently this option should not appear here, right?

**Comment by dBucik** [comment]
Apple and Google should now be removed. Previous selection will not be applied as the URL for the selection without Google is different, meaning the cookie is not read.
