### ISSUE TITLE
Login via LS-AAI using institutional credentials

### ISSUE THREAD

**Issue by rini21** [ejp-rd-vp/vp-portal-issues#29]
**Describe your problem.**

Institutional login via LS-AAI returns an error page

**If it is a bug name steps to reproduce**

1. Go to https://vp.ejprarediseases.org/
2. Click on Login
3. Click 'Sign in using LS-AAI'
4. In 'Login with' text input, enter University of Leicester and enter institutional credentials.
5. See error

**If it is a bug complete the following information:**

- Version: 1.0
- OS: Linux
- Browser: Firefox

**Describe the solution you'd like**

Login and query VP-Portal using my institutional credentials. 

**Additional context**
The error page that's returned:
![image](https://github.com/ejp-rd-vp/vp-portal-issues/assets/24955128/f38de6ac-3228-4fb5-a944-81d6edab7b95)
@HaddadTala @vabishaa @Ammarbr

**Comment by kkr-ait** [comment]
And I can confirm that I have exactly the same issue with using my ORCID account.

**Comment by dBucik** [comment]
Fixed by @Ammarbr - seems it was problem with the "Attribute mapper" configuration.
