### ISSUE TITLE
Vp-portal fails to redirect users to the login page when using Safari browser

### ISSUE THREAD

**Issue by ammarbarakat** [ejp-rd-vp/vp-portal-issues#31]
**Describe your problem.**

Vp-portal fails to redirect users to the login page when using Safari browser.

**If it is a bug name steps to reproduce**

1. Open Safari browser.
2. Enter the URL for vp-portal (vp.ejprarediseases.org) and press Enter.
3. Click on the login button.
4. Observe that the login page does not load and the user remains on the current page.

**If it is a bug complete the following information:**

- Version: 0.1.0
- OS: OS X
- Browser: safari

**Describe the solution you'd like**

Upon accessing vp-portal using the Safari browser, users should be redirected to the login page where they can enter their credentials to gain access to the advanced filters.

**Comment by kkr-ait** [comment]
It is not only a Safari problem - I have experienced the same using Firefox on my Mac and still have the issue (at least on production)

**Comment by kkr-ait** [comment]
Sorry @Ammarbr - I opened up another GIT issue for this, flagged the other one as duplicate (will close the other one)

**Comment by kkr-ait** [comment]
Btw, @Ammarbr  - I cannot access the development machine on my mac, as it has a certificate problem. Even if I ignore the certificate problem and open the page, I am redirected to Apache 404 default page.
