### ISSUE TITLE
Login via Google / Add note to login screen

### ISSUE THREAD

**Issue by kkr-ait** [ejp-rd-vp/vp-portal-issues#34]
The VP portal does not allow a login via Google, however it is possible to link a Google account to AAI in general during registration with AAI. Currently there is no way to configure AAI in a way that Google account registration can be prevented. 
In order to avoid questions, we should have a link at the EJP-RD portal login screen  stating that Google accounts cannot be used with EJP-RD.

**Comment by kkr-ait** [comment]
@dBucik @HaddadTala - some sort of message should still be defined

**Comment by ammarbarakat** [comment]
Seeing that this is tied to v1.0.0 and we've already rolled out the release, I'm guessing the issue is solved by now.
