### ISSUE TITLE
Design and Content Improvements VP frontend

### ISSUE THREAD

**Issue by vabishaa** [ejp-rd-vp/vp-portal-issues#4]
Update the landing page after finalizing the content by Ana Rath and Franz Schäfer

1. - [x] Update the intro text 
2. - [x] Redesign the "VP-PORTAL" text in the header 
3. - [x] VP Network resource page: change hover text of VP Content Discovery tag -> change Discovery Portal to VP Portal
4. -  [x] resource discovery: update notice text to "Please Log in to activate these filters"
5. - [x] change imprint to "Legal Notice"
6. - [x] change text beneath GUIDANCE-Button to "Find out how to make your data more FAIR"
7. - [x] link GUIDANCE-Button to https://www.ejprarediseases.org/fairification/

- [x] after accepting cookies during search it will stop the querying and the cookies bar will still be visible -> bug was fixed but check again
- [x] if possible a better representation of stakeholders in the picture (@vabishaa )

**Comment by vabishaa** [comment]
@HaddadTala:Feel free to add

**Comment by HaddadTala** [comment]
Dear @vabishaa , please see the cleaned and reviewed intro text in the document. I'm also copying here:

The Virtual Platform (VP) is a growing **network** of Findable, Acessible , Interoperable and Reusable (FAIR) resources, ready to serve the rare disease (RD) research community. 

It includes catalogues of resources, registries, biobanks, knowledge bases and tools compliant with agreed standards. 

The **VP Portal** allows you to search the VP network resources at once in real time to find those of interest to your research.
