### ISSUE TITLE
Explanatory text for LS-AAI Login

### ISSUE THREAD

**Issue by HaddadTala** [ejp-rd-vp/vp-portal-issues#42]
Modify text to:

LifeScience Login is an authentication service provided by EOSC-Life. It enables researchers to use their home organisation credentials or community or other identities to sign in and access data and services they need.

If you don't have a LifeScience RI account, you will be guided to create one the first time you log in.

**Comment by HaddadTala** [comment]
@ammarbarakat

**Comment by ammarbarakat** [comment]
See #43
