### ISSUE TITLE
Decision about Disclaimer removal

### ISSUE THREAD

**Issue by vabishaa** [ejp-rd-vp/vp-portal-issues#8]
As I assume the June Release V1.0  is not a Beta Version anymore should we remove the Disclaimer text for the release
(Check https://directory.ejp.vp.bbmri-eric.eu/discovery)

**Comment by kkr-ait** [comment]
My personal opinion is: keep it on the resource discovery page - as people are experimenting with search, they may have ideas and feedback and can directly provide it by clicking one button.

**Comment by Ammarbr** [comment]
https://github.com/ejp-rd-vp/vp-dp-frontend/issues/38
