### ISSUE TITLE
Login via ORCID

### ISSUE THREAD

**Issue by kkr-ait** [ejp-rd-vp/vp-portal-issues#9]
**Describe your problem.**
I tried to login via my ORCID account using LS-AAI today, but failed to do so.

**If it is a bug name steps to reproduce**

1. Go to https://directory.ejp.vp.bbmri-eric.eu/discovery
2. Click on "Login"
3. Follow "Life Science AAI"

- OS: Windows
- Browser: Firefox, latest version

**Describe the solution you'd like**

I am presented with the possibility to login via ORCID. The login works and I can also grant LS-AAI the permission to do so. One thing is, that I now have to create a LS-AAI account (not sure if it is really intended to create an account at this stage) and verify my e-mail-address. So far so good. Once the e-mail-address is verified, I am redirected back to the portal, with out success. I am presented with a page that reads:

```
Access not allowed
The service EJP RD Virtual Platform you are accessing requires specific Virtual Organization (VO) or Group membership.
In order to be able to access the service, you need to be a member of one of the following VOs or Groups:

    [VO: lifescience_test](https://signup.aai.lifescience-ri.eu/fed/registrar/?vo=lifescience_test)
```

**Additional context**
None

**Comment by kkr-ait** [comment]
@vabishaa , @HaddadTala (this has been discussed in today's L1/L2 call anyway and could be followed-up in next weeks OA call)

**Comment by HaddadTala** [comment]
Dear @kkr-ait , yes also if you log in with your LD-AAI user account, it has the same issue. We need to andd and tag Dominik here to resolve the issue. I'm sending an email to him now. @vabishaa has probably updated you with this info.

**Comment by rini21** [comment]
The same issue persists for institutional LS-AAI login (not via ORCID). The 'Login via Life Science AAI' button redirects to 
https://webapp.aai.lifescience-ri.eu/error - does not even let the user choose institutional/ORCID.
![image](https://github.com/ejp-rd-vp/vp-portal-issues/assets/24955128/2298781a-f117-4544-8b4f-842d9e06a7b3)

**Comment by dBucik** [comment]
> The same issue persists for institutional LS-AAI login (not via ORCID). The 'Login via Life Science AAI' button redirects to https://webapp.aai.lifescience-ri.eu/error - does not even let the user choose institutional/ORCID. ![image](https://user-images.githubusercontent.com/24955128/250068082-2298781a-f117-4544-8b4f-842d9e06a7b3.png)

This issue should now be solved. Fortunately has not been related to ORCID rather than the integration of LS AAI and EJP-RD KeyCloak.

**Comment by dBucik** [comment]
> **Describe your problem.** I tried to login via my ORCID account using LS-AAI today, but failed to do so.
> 
> **If it is a bug name steps to reproduce**
> 
> Steps to reproduce the behavior:
> 
>     1. Go to https://directory.ejp.vp.bbmri-eric.eu/discovery
> 
>     2. Click on "Login"
> 
>     3. Follow "Life Science AAI"
> 
>     4. See error
> 
> 
>     * OS: Windows
> 
>     * Browser: Firefox, latest version
> 
> 
> **Describe the solution you'd like**
> 
> I am presented with the possibility to login via ORCID. The login works and I can also grant LS-AAI the permission to do so. One thing is, that I now have to create a LS-AAI account (not sure if it is really intended to create an account at this stage) and verify my e-mail-address. So far so good. Once the e-mail-address is verified, I am redirected back to the portal, with out success. I am presented with a page that reads:
> 
> ```
> Access not allowed
> The service EJP RD Virtual Platform you are accessing requires specific Virtual Organization (VO) or Group membership.
> In order to be able to access the service, you need to be a member of one of the following VOs or Groups:
> 
>     [VO: lifescience_test](https://signup.aai.lifescience-ri.eu/fed/registrar/?vo=lifescience_test)
> ```
> 
> **Additional context** None

Regarding this - there has been a problem with ORCID in LS AAI for the last week. Fortunately, it should be solved. If you, however, tried to use ORCID during this time window, I strongly advise removing cookies in the browser, as it might have something cached pointing to the old integration. I also strongly advise removing the previous selection if not have done it already and trying to log in via ORCID once again. If the login succeeds, you do not need to repeat the procedure anymore.
![Untitled 16 46 01](https://github.com/ejp-rd-vp/vp-portal-issues/assets/36446870/8fdb3c42-2a94-4a49-9cad-035ee0b63aaf)

For any further problems with ORCID please send as many emails as possible to support@aai.lifescience-ri.eu so we can create pressure on the e-infrastructures providing the integration.
